/*
 * generated by Xtext 2.10.0
 */
package at.ac.uibk.gherkin.tests

import at.ac.uibk.gherkin.gherkin.Feature
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GherkinInjectorProvider)
class GherkinParsingTest{

	@Inject
	ParseHelper<Feature> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
Feature: Ensuring that javascript works in all supported browsers
    In order to make sure that javascript works
    As a developer
    I visit a page with javascript and the script should be executed

    Scenario Outline: The javascript rendered "Test" should be visible
        Given I am using <browser>
         When I visit the salad test url "browser/js.html"
          And I wait 1 second
         Then I should see "Test" somewhere in the page

    Examples:
    | browser   |
    | chrome    |
    | firefox   |
    | phantomjs |
		''')
		Assert.assertNotNull(result)
	}

}
