/*
 * generated by Xtext 2.10.0
 */
package at.ac.uibk.gherkin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GherkinRuntimeModule extends AbstractGherkinRuntimeModule {
	
}