/*
 * generated by Xtext 2.10.0
 */
package at.ac.uibk.gherkin

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GherkinStandaloneSetup extends GherkinStandaloneSetupGenerated {

	def static void doSetup() {
		new GherkinStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
